from __future__ import annotations

import re
import unicodedata
from pathlib import Path

from .io import protected_write_text
from .models import Author, PaperRecord, VerificationResult


_BIB_ESCAPE = str.maketrans(
    {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
    }
)


def export_bibtex(path: str | Path, results: list[VerificationResult]) -> None:
    verified = _verified_results(results)
    keys: set[str] = set()
    entries = [
        _bibtex_entry(result, _unique_key(_citation_key(result.record), keys))
        for result in verified
        if result.record is not None
    ]
    _write(path, "\n\n".join(entries) + ("\n" if entries else ""))


def export_markdown(path: str | Path, results: list[VerificationResult]) -> None:
    verified = [result for result in results if result.is_citable and result.record]
    source_errors = [result for result in results if result.status == "SOURCE_UNAVAILABLE"]
    unresolved = [
        result
        for result in results
        if not result.is_citable and result.status != "SOURCE_UNAVAILABLE"
    ]
    lines = ["# Verified references", "", "> Generated by clean-citaton. Read-only program snapshot.", ""]
    if verified:
        for index, result in enumerate(verified, 1):
            record = result.record
            assert record is not None
            lines.append(f"{index}. {_markdown_citation(record, result.status)}")
    else:
        lines.append("No references met the verification threshold.")

    lines.extend(["", "## Verification audit", ""])
    for result in verified:
        record = result.record
        assert record is not None
        lines.append(
            f"- **{_md_escape(record.title)}** — source: [{record.source}]({record.source_url}); "
            f"status: {result.status}; authority: {result.authority_level}; "
            f"match score: {result.score:.2f}; retrieved: {record.retrieved_at}."
        )
    if source_errors:
        lines.extend(["", "## Source access errors", ""])
        lines.append(
            "These entries were not disproved; one or more required sources could not be read."
        )
        lines.append("")
        for result in source_errors:
            detail = "; ".join(result.source_failures or result.errors) or result.reason
            credential = (
                f" Required credential: `{result.required_credential}`."
                if result.required_credential
                else ""
            )
            lines.append(
                f"- **{_md_escape(result.hint.title)}** — {result.reason} "
                f"Source detail: {_md_escape(detail)}.{credential}"
            )
    if unresolved:
        lines.extend(["", "## Unresolved inputs", ""])
        for result in unresolved:
            lines.append(f"- **{_md_escape(result.hint.title)}** — {result.reason}")
    _write(path, "\n".join(lines).rstrip() + "\n")


def _verified_results(results: list[VerificationResult]) -> list[VerificationResult]:
    verified: list[VerificationResult] = []
    seen: set[str] = set()
    for result in results:
        if not result.is_citable or result.record is None:
            continue
        identity = (
            result.record.doi
            or result.record.arxiv_id
            or result.record.openreview_id
            or f"{result.record.title}|{result.record.year}"
        )
        if identity.casefold() not in seen:
            seen.add(identity.casefold())
            verified.append(result)
    return verified


def _bibtex_entry(result: VerificationResult, key: str) -> str:
    record = result.record
    assert record is not None
    native = record.extra.get("raw_bibtex")
    if native and result.status not in {"OPENREVIEW_SUBMISSION", "REJECTED_OPENREVIEW"}:
        return _replace_bibtex_key(str(native), key)
    entry_type = _bibtex_type(record, result.status)
    fields: list[tuple[str, str | None]] = [
        ("title", record.title),
        ("author", " and ".join(_bibtex_author(author) for author in record.authors)),
        ("year", str(record.year) if record.year else None),
    ]
    if entry_type == "article":
        fields.append(("journal", record.venue))
    elif entry_type == "inproceedings":
        fields.append(("booktitle", record.venue))
    else:
        fields.append(
            (
                "howpublished",
                "OpenReview public submission"
                if result.status in {"OPENREVIEW_SUBMISSION", "REJECTED_OPENREVIEW"}
                else record.venue,
            )
        )
    note = None
    if result.status == "REJECTED_OPENREVIEW":
        note = "Rejected submission; not an accepted proceedings publication"
    elif result.status == "OPENREVIEW_SUBMISSION":
        note = "Public submission; final acceptance was not verified"
    fields.extend(
        [
            ("publisher", record.publisher),
            ("volume", record.volume),
            ("number", record.issue),
            ("pages", record.pages),
            ("doi", record.doi),
            ("eprint", record.arxiv_id),
            ("archivePrefix", "arXiv" if record.arxiv_id else None),
            ("primaryClass", record.extra.get("primary_category") if record.arxiv_id else None),
            ("note", note),
            ("url", record.url),
        ]
    )
    rendered = [f"@{entry_type}{{{key},"]
    present = [(name, value) for name, value in fields if value]
    for index, (name, value) in enumerate(present):
        comma = "," if index < len(present) - 1 else ""
        rendered.append(f"  {name} = {{{_bib_escape(str(value))}}}{comma}")
    rendered.append("}")
    return "\n".join(rendered)


def _bibtex_type(record: PaperRecord, status: str) -> str:
    if status in {"OPENREVIEW_SUBMISSION", "REJECTED_OPENREVIEW"}:
        return "misc"
    if record.source == "openreview" or record.entry_type in {"proceedings-article", "proceedings"}:
        return "inproceedings"
    if record.venue and (record.doi or record.entry_type in {"journal-article", "article"}):
        return "article"
    return "misc"


def _bibtex_author(author: Author) -> str:
    if author.literal:
        return _bib_escape(author.literal)
    if author.family and author.given:
        return f"{_bib_escape(author.family)}, {_bib_escape(author.given)}"
    return _bib_escape(author.display_name)


def _bib_escape(value: str) -> str:
    return value.translate(_BIB_ESCAPE)


def _citation_key(record: PaperRecord) -> str:
    author = record.authors[0].family or record.authors[0].display_name if record.authors else "anon"
    words = [word for word in _ascii_slug(record.title).split("-") if len(word) > 2]
    title_word = words[0] if words else "work"
    return f"{_ascii_slug(author).replace('-', '') or 'anon'}{record.year or 'nd'}{title_word}"


def _unique_key(base: str, keys: set[str]) -> str:
    key = base
    suffix = ord("a")
    while key in keys:
        key = f"{base}{chr(suffix)}"
        suffix += 1
    keys.add(key)
    return key


def _ascii_slug(value: str) -> str:
    value = unicodedata.normalize("NFKD", value).encode("ascii", "ignore").decode("ascii").lower()
    return re.sub(r"^-+|-+$", "", re.sub(r"[^a-z0-9]+", "-", value))


def _markdown_citation(record: PaperRecord, status: str) -> str:
    authors = ", ".join(_md_escape(author.display_name) for author in record.authors) or "Unknown author"
    year = str(record.year) if record.year else "n.d."
    title = _md_escape(record.title)
    title_part = f"[{title}]({record.url})" if record.url else title
    venue = f" *{_md_escape(record.venue)}*." if record.venue else ""
    details = ""
    if record.volume:
        details += f" {record.volume}"
        if record.issue:
            details += f"({record.issue})"
    if record.pages:
        details += f", {record.pages}"
    if details:
        details += "."
    doi = f" https://doi.org/{record.doi}" if record.doi else ""
    label = ""
    if status == "REJECTED_OPENREVIEW":
        label = " [Rejected OpenReview submission; not formally published.]"
    elif status == "OPENREVIEW_SUBMISSION":
        label = " [OpenReview submission; acceptance not verified.]"
    return f"{authors} ({year}). {title_part}.{venue}{details}{doi}{label}".replace("..", ".")


def _md_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace("[", "\\[").replace("]", "\\]")


def _write(path: str | Path, content: str) -> None:
    protected_write_text(path, content)


def _replace_bibtex_key(value: str, key: str) -> str:
    return re.sub(r"(@[A-Za-z]+\s*\{)\s*[^,]+,", rf"\g<1>{key},", value, count=1).strip()
